### ISSUE TITLE
Suggestion: Can you provide a short example on how to use the analyzer object?

### ISSUE THREAD

**Issue by eformx** [knuppe/SharpNL#11]
analyzer.Analyze(doc); ???  How  do we view the sentences, tokens, parts of speech from this object?

Thanks!

**Comment by knuppe** [comment]
I'm still documenting the library, but look if this helps.

https://github.com/knuppe/SharpNL/wiki/Analyzers

**Comment by eformx** [comment]
Thanks knuppe!  The second link helped.  This is my working code, asp.net vb.net...

'one shot analyzer, vb.net
        Dim modelAnalyzer As AggregateAnalyzer = New AggregateAnalyzer
        modelAnalyzer.Add(curDir & "\en-sent.bin")
        modelAnalyzer.Add(curDir & "\en-token.bin")
        modelAnalyzer.Add(curDir & "\en-pos-maxent.bin")

        Dim doc As New Document("en", text)
        modelAnalyzer.Analyze(doc)

        Dim sentCount As Integer = doc.Sentences.Count

        For i As Integer = 0 To sentCount - 1
            Dim _sentence As String = doc.Sentences(i).Text
            Dim tokenCount As Integer = doc.Sentences(i).Tokens.Count
            For a As Integer = 0 To tokenCount - 1
                Dim sToken As String = doc.Sentences(i).Tokens(a).Lexeme
                Dim sPartOfSpeech As String = doc.Sentences(i).Tokens(a).POSTag
                Dim sSentence As String = doc.Sentences(i).Tokens(a).Sentence.Text
            Next
        Next
