### ISSUE TITLE
how to use SharpNL.Lemmatizer and SharpNL.DocumentCategorizer Classifier etc...

### ISSUE THREAD

**Issue by johnearnshaw** [knuppe/SharpNL#15]
your library is very good but how do you use some parts of it?
I get the models from OpenNLP and can use the tokenizer, chunker, namefinder etc.. but how do you use the lemmatizer, documentcategorizer and classifier etc... I cant find an en-lemma.bin, do you have models for working with these functions?

**Comment by knuppe** [comment]
Hi,

The library only supports lemmatization through a dictionary. I wrote the code to implement a ML tool, but I ended up not continuing to build it. Maybe in the future ;)

I'm still doing the documentation in my spare time... Today I added the doccat in the wiki, maybe it helps you a bit.

* [Document Categorizer](https://github.com/knuppe/SharpNL/wiki/Document-Categorizer)
