### ISSUE TITLE
Documentation for the POS Tagger

### ISSUE THREAD

**Issue by Sorrien** [knuppe/SharpNL#16]
The documentation you have written thus far has been extremely helpful, and by following your pattern of implementation I have managed to implement the part of speech tagger. I can feed it a string and get back a result that looks useful, but I have trouble figuring out what the acronyms mean. I would greatly appreciate a new page in the wiki for part of speech tagging. Thank you for the fantastic tool, and keep up the good work!

**Comment by Sorrien** [comment]
I added a wiki page for the part of speech tagging after putting hours of research into finding all the information I needed to use it. I haven't added the training documentation, but the essentials are there.

**Comment by knuppe** [comment]
Hello Sorrien, thanks for your contribution... But the tags are different for each language.
For instance `V` in the english models is a verb tag, in portuguese we have different tags like: `v-fin` (finitive verbs), `v-inf`(infinitive verbs), `v-pcp` (particle verbs), etc.

Each tag is just a string value, which varies depending on the way that the model was trained. So, the tagset that you documented is valid only for the "en-pos-xxx.bin" models that the opennlp dev´s created some time ago.

**Comment by Sorrien** [comment]
Thank you for your reply. Do you know of any newer or better models I could use? I am new to the world of natural language processing. I am utilizing your library for the purpose of a dynamic text based command system, so there are a lot of verbs, and sometimes the only word is a verb. I've had issues with certain words that are verbs, and nouns always being identified as nouns. Also, I will update the wiki page to note that the tags are for that specific model.

**Comment by knuppe** [comment]
Unfortunately no, usually better models are not public due to licenses and copyright stuff. You could try to ask for other opennlp users in the [mailing lists](http://opennlp.apache.org/mail-lists.html) of the main project, they may know if there is a public model that kits what you need.

Thanks for your contribution on the wiki page :+1:
