### ISSUE TITLE
Suggestions for building models for Chinese

### ISSUE THREAD

**Issue by Davtomas** [knuppe/SharpNL#17]
I am not able to find any link to existing OpenNLP models for Chinese. Anyone can offer some tutorials and preferably some template files that are needed to build these models? 

The other project 
https://github.com/quicquam/opennlp4net

has some information on training data. 

Anyone has tested the difference between SharpNL and OpenNLP4net. It seems SharpNL is more active, hopefully, we can have more information on how to 
(a) train additional terms into existing models (english)
(b) start basic Chinese Models building projects

**Comment by knuppe** [comment]
Hi Tomas, sorry for the late reply.

The SharpNL is still far from what I want, but I have little time to work deeper to implement the improvements that I would like.

I do not know in detail the chinese language, but based on what I saw in the code there is not much customized code for the chinese. 

My best advice to you is to try to get contact other users in the opennlp mail-lists. They may have some better experiences with the chinese language and models than me.

http://opennlp.apache.org/mail-lists.html

best regards,
Gustavo K.
