### ISSUE TITLE
issue with Span.GetCoveredText() and "en-ner-money.bin" model

### ISSUE THREAD

**Issue by johnearnshaw** [knuppe/SharpNL#18]
Hey,

When tokenizing the string "There are many $1,000 banknotes or bills", the $ is split from the 1,000...
Using NameFinder with the ner-money model returns an array of type "Span"...
So when using Span.GetCoveredText([wordsArray]) a string containing whitespace between the currency symbol and the figure (eg. "$ 1,000") is returned...
This is incorrect covered text...

Thought I'd raise it and see what your thoughts are?

Cheers.

**Comment by knuppe** [comment]
Hi, 

The tokenizers are designed to split the symbol/punctuation from the other words or numbers. To make it clear what you are doing, could you provide a sample code?

**Comment by johnearnshaw** [comment]
Hey, sorry for the late reply. I've been really busy.
I knocked together some code to show what I mean, not tested it though:

`namespace MoneyFinder
{
    using System;
    using System.IO;
    using System.Linq;

    using SharpNL;
    using SharpNL.Analyzer;
    using SharpNL.SentenceDetector;
    using SharpNL.Tokenize;
    using SharpNL.POSTag;
    using SharpNL.NameFind;

    class Program
    {
        static string ModelsDir = "MODELSDIRECTORY";

        static void Main(string[] args)
        {
            var moneyStr = "There are many $1,000 banknotes or bills.";
            Console.WriteLine(moneyStr);

            var doc = new Document("en", moneyStr);

            var analyzer = new AggregateAnalyzer
            {
                new SentenceDetectorAnalyzer(new SentenceDetectorME(new SentenceModel(ModelsDir + "en-sent.bin"))),
                new TokenizerAnalyzer(new TokenizerME(new TokenizerModel(ModelsDir + "en-token.bin"))),
                new POSTaggerAnalyzer(new POSTaggerME(new POSModel(ModelsDir + "en-pos-maxent.bin"))),
            };

            analyzer.Analyze(doc);

            TokenNameFinderModel model;
            using (Stream s = new FileStream(ModelsDir + "en-ner-money.bin", FileMode.Open))
            {
                model = new TokenNameFinderModel(s);
            }

            var moneyFinder = new NameFinderME(model);

            foreach (var s in doc.Sentences)
            {
                string[] words = s.Tokens.Select(x => x.Lexeme).ToArray();

                var foundMoney = moneyFinder.Find(words);
                if (foundMoney != null)
                {
                    foreach (var m in foundMoney)
                    {
                        var mTxt = m.GetCoveredText(words);
                        var mPos = m.GetSpanPosition(s);
                        Console.WriteLine(string.Format("Found money in sentence tokens - spannedText = \"{0}\" @ startPos = {1}, stringLength = {2}", 
                            mTxt, mPos.Start, mPos.Length));

                        // Write out the string from original text based on the found span, replacing whitespace with _ for visibility.
                        Console.WriteLine(string.Format("String from original text - \"{0}\"",
                            moneyStr.Substring(mPos.Start, mPos.Length).Replace(" ", "_")));
                    }
                }
            }

            Console.WriteLine("\r\nPress a key to exit...");
            Console.ReadKey();
        }
    }
}`

**Comment by johnearnshaw** [comment]
I know it looks like it could have been tested, just don't have vs on the machine I wrote it on, used notepad++ ;)

**Comment by knuppe** [comment]
As I remember, the span positions are related to the tokens not the text itself. I'll find some time to change your code to return the desired result. I've been quite busy too! :disappointed:

**Comment by johnearnshaw** [comment]
Yes, that's what I was getting at. The span positions are related to the tokens and presumes there is a space between each token when working out the positions but I'm not sure it works this way in OpenNLP.

The '$' in the tokenized document is a separate token when parsing $1,000. So span position of the money finder is thought to be '$ 1,000' due to the presumed whitespace tokenization even though the tokenizer is not whitespace based.

Thanks for getting back to me btw :)

**Comment by knuppe** [comment]
I was looking into your code yesterday, and a saw that you are trying to get the entity position based on the `Spans` returned by the `NameFinder`. However the problem is that `Spans` in the namefinder are related to the Tokens not to the input text.

So, you must to change the logic, otherwise It'll not work properly...
:+1:
