### ISSUE TITLE
DictionaryDetokenizer issue

### ISSUE THREAD

**Issue by normanpaterson** [knuppe/SharpNL#21]
In the following code, I get the error "An item with the same key has already been added" at the dictionary variable creation:
'''
 DetokenizationDictionary.Operation[] operations = new DetokenizationDictionary.Operation[tokens.Length];
            for (int i = 0; i < tokens.Length; i++)
            {
                operations[i] = DetokenizationDictionary.Operation.MoveLeft;
            }

            DetokenizationDictionary dictionary = new DetokenizationDictionary(
              tokens, operations);
            DictionaryDetokenizer detokenizer = new DictionaryDetokenizer(
              dictionary);
            var blah = detokenizer.Detokenize(tokens, " ");
'''

**Comment by knuppe** [comment]
Hi,

you should use the detokenizer in a different way, take a look in the tests in the following link:

https://github.com/knuppe/SharpNL/blob/development/src/SharpNL.Tests/Tokenize/DictionaryDetokenizerTest.cs

**Comment by normanpaterson** [comment]
Thank you so much for helping, it works!  Here's my code:

  private static IDetokenizer prepareDeTokenizer()
        {
            DetokenizationDictionary dict = null;
            var assembly = Assembly.GetExecutingAssembly();
            using (Stream stream =
assembly.GetManifestResourceStream(deTokenizerModelPath))
            {
                dict = new DetokenizationDictionary(stream);
            }
            return new DictionaryDetokenizer(dict);
        }


var detokenizer = prepareDeTokenizer();
            var blah = detokenizer.Detokenize(tokens, null);
