### ISSUE TITLE
GenericModelWriter does not support NaiveBayes

### ISSUE THREAD

**Issue by harsimranb** [knuppe/SharpNL#25]

**Comment by knuppe** [comment]
Hi, thanks for the fixes! I'll accept your changes soon, I abandoned Windows last month... Now I need to fix the code, in order to make it work on linux. A few tests are not working properly :disappointed: 

Good to see more people working in the project!
:+1:

**Comment by harsimranb** [comment]
Sounds good.  You've done some solid work on this library, its very helpful.  If I get time, I'll try to help out on the mono compatibility issues.
