### ISSUE TITLE
Error in en-ner-person.zip (need a project to be built)

### ISSUE THREAD

**Issue by vgopinath** [knuppe/SharpNL#28]
Hi.

Downloaded Nuget package.
 using (var modelFile = new FileStream(@"C:\Projects\Projects\NumlConsole\All Reports\VSHospital\en-ner-person.zip", FileMode.Open))
                    model = new SharpNL.Tokenize.TokenizerModel(modelFile);

after above tokerizer, model has this exception.
MaxentModel = 'model.MaxentModel' threw an exception of type 'System.Collections.Generic.KeyNotFoundException'

Pls help a fix. 
BTW, we are working on NLP medical, need some help can you provider your contact?

Thanks.

Gopi

**Comment by knuppe** [comment]
Hi Gopi, 

I noticed that you are using a ".zip" model file, how did you create this model file? I suspect there is something missing in the model file, so the exception is occurring.

In the following test I use the "default" opennlp models to test the library, and I never had this exception.
https://github.com/knuppe/SharpNL/blob/development/src/SharpNL.Tests/Compatibility/TokenizerTest.cs

I'm little busy these days, but you can ask things here, and I'll replay as soon as possible.

Gustavo K.

**Comment by eformx** [comment]
@vgopinath what kind of help do you need?  I have quite a bit of NLP expertise.

**Comment by vgopinath** [comment]
Can u send an email to vgopinath AT hotmail will discuss further 1to1.
Thx

**Comment by vgopinath** [comment]
![image](https://cloud.githubusercontent.com/assets/16788427/17074572/926e36b4-504a-11e6-8616-0c13d18b7239.png)

Thanks Gustavo... Attached is the image or VS 2015 error. I've used *-bin*, no difference.
I'll try tokenizer model next..

**Comment by knuppe** [comment]
@vgopinath I was trying to replicate your problem, and I realized that you are using a "en-ner-person.bin" model on the tokenizer tool...

Each tool has its own model, eg. to tokenize a sentence you should use the "en-token.bin" in the tool TokenizerME.

:wink:

**Comment by vgopinath** [comment]
:) thanks for spotting... I've change to TokenNameFinderModel, now it works... :)
