### ISSUE TITLE
Compile issue with Visual Studio 2015 community edition

### ISSUE THREAD

**Issue by chrischou** [knuppe/SharpNL#29]
Can latest SharpNL be compiled with Visual Studio 2015 community edition (update 3, latest at time of writing)? 
I got a lot of compile error like: \SharpNL\src\SharpNL\BaseObject.cs(42,48,42,100): error CS8026: Feature 'expression-bodied property' is not available in C# 5.  Please use language version 6 or greater.

But Visual Studio 2015 community is capable of working with C# 6. Any hint?

**Comment by knuppe** [comment]
Hi, just change the version to 6.0 in `Properties => Build Tab => Advanced button => Language Version`

VS 2015 should support C# 6.0
