### ISSUE TITLE
Multi-threaded ParseLine?

### ISSUE THREAD

**Issue by aeshirey** [knuppe/SharpNL#32]
It appears to me that sentence parsing is single-threaded only. The following code indeterminately throws either a `System.Collections.Generic.KeyNotFoundException` or `System.NullReferenceException` within the `ParserTool.ParseLine` call:

```
const string parserModelFile = "en-parser-chunking.bin";

FileStream modelStream = new FileStream(parserModelFile, FileMode.Open, FileAccess.Read);
ParserModel parserModel = new ParserModel(modelStream);
IParser parser = ParserFactory.Create(parserModel);

string[] sentences = new[]
{
    "The quick brown fox jumps over a lazy dog.",
    "Pack my box with five dozen liquor jugs.",
    "Jackdaws love my big sphinx of quartz.",
    "The five boxing wizards jump quickly.",
    "How vexingly quick daft zebras jump!",
    "Bright vixens jump; dozy fowl quack.",
    "Sphinx of black quartz, judge my vow."
};

IList<Parse[]> parsed = sentences
    .AsParallel()
    .WithDegreeOfParallelism(5)
    .Select(sentence => ParserTool.ParseLine(sentence, parser, 1))
    .ToList();
```

Is multi-threaded parsing supported by some other mechanism?

**Comment by knuppe** [comment]
Hi, the multi threading support is a bit weird in the original library... In order to make it work, you need one `IParser` per thread. 

I didn't test this, but as far as I know, the original opennlp library is designed to share only the model instances, not the tools.
