### ISSUE TITLE
TokenizerME.Train() exception when using UseAlphaNumericOptimization=true

### ISSUE THREAD

**Issue by casiobearing** [knuppe/SharpNL#33]
The following exception occurs when training if used with a new TokenizerFactory("en", null, true);

System.ArgumentOutOfRangeException 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at SharpNL.ML.Model.AbstractDataIndexer.SortAndMerge(List`1 eventsToCompare, Boolean sort)
   at SharpNL.ML.Model.TwoPassDataIndexer.PerformIndexing()
   at SharpNL.ML.Model.AbstractDataIndexer.Execute()
   at SharpNL.ML.MaxEntropy.GISTrainer.TrainModel(Int32 iterations, IDataIndexer di, IPrior modelPrior, Int32 modelCutoff, Int32 threads)
   at SharpNL.ML.MaxEntropy.GIS.TrainModel(Int32 iterations, IDataIndexer indexer, Boolean smoothing, IPrior modelPrior, Int32 cutoff, Int32 threads, Monitor monitor)
   at SharpNL.ML.MaxEntropy.GIS.DoTrain(IDataIndexer indexer)
   at SharpNL.ML.Model.AbstractEventTrainer.Train(IObjectStream`1 events)
   at SharpNL.Tokenize.TokenizerME.Train(IObjectStream`1 samples, TokenizerFactory factory, TrainingParameters parameters, Monitor monitor)
   at SharpNL.Tokenize.TokenizerME.Train(IObjectStream`1 samples, TokenizerFactory factory, TrainingParameters parameters)

**Comment by knuppe** [comment]
You could send more details? The exception is showing something in the data indexing, and I can't reproduce the exception :disappointed:

**Comment by casiobearing** [comment]
It appears to depend on the content of the training data file. Try using a training file containing a single line with a single word e.g. "xyz". (Also fails with two words and 2 lines).
My code up to the failure point is
            TokenizerFactory Factory;
            TokenizerModel model;
            FileStream fileStreamTraining;
            PlainTextByLineStream lineStream;
            TokenSampleStream sampleStream;
            TrainingParameters Tp;

            Tp = new TrainingParameters();
            Tp.Set(Parameters.Iterations, "100");
            Tp.Set(Parameters.Cutoff, "0");
            Factory = new TokenizerFactory("en", null, true);
            fileStreamTraining = new FileStream(InputCorpusFile, FileMode.Open);
            lineStream = new PlainTextByLineStream(fileStreamTraining, Encoding.UTF8);
            sampleStream = new TokenSampleStream(lineStream);
            model = TokenizerME.Train(sampleStream, Factory, Tp);

Regards :o)

**Comment by jeffboulanger** [comment]
Same problem, 1 word training data, any update on this?

**Comment by jeffboulanger** [comment]
Example Code:
`
        var trainingDataService = Container.Resolve<ITrainingDataService>();
        var categorizerFactory = new DocumentCategorizerFactory();

        DocumentCategorizerModel model;

        using (var sampleStream = await trainingDataService.CreateDocumentCategoryStream())
        {
            model = DocumentCategorizerME.Train(
                "en",
                sampleStream,
                GetMaxEntTrainingParameters(),
                categorizerFactory);
        }

        public static TrainingParameters GetMaxEntTrainingParameters()
        {
            var trainingParameters = new TrainingParameters();
            trainingParameters.Set("Algorithm", "MAXENT");
            trainingParameters.Set("TrainerType", "Event");
            trainingParameters.Set("Iterations", "5000");
            trainingParameters.Set("Cutoff", "4");
            trainingParameters.Set("Threads", "8");
            return trainingParameters;
        }`

Simple Data:
`Number 12345 
Number 0934096
Number 65456 
Number 5675 
Number 4 `

**Comment by knuppe** [comment]
> It appears to depend on the content of the training data file. Try using a training file containing a single line with a single word e.g. "xyz". (Also fails with two words and 2 lines).

I think the documentation is a little bit unclear, even in the [documentation ](http://opennlp.apache.org/docs/1.8.0/manual/opennlp.html#tools.doccat) of the original library.

In the [constructor](https://github.com/knuppe/SharpNL/blob/development/src/SharpNL/DocumentCategorizer/DocumentSample.cs#L48) the `text` argument should be the tokens of the sentence, not a single word.

```csharp
public DocumentSample(string category, string[] text) {
```

I wrote this test to try reproduce the problem, but without success. :pensive: 

```csharp

using System;
using System.Collections.Generic;

using NUnit.Framework;
using SharpNL.DocumentCategorizer;
using SharpNL.Utility;

namespace SharpNL.Tests {
    [TestFixture]
    public class Github {
        
        [Test]
        public void Issue33() {
            var list = new List<DocumentSample> ();
            var rnd = new Random (unchecked((int)DateTime.Now.Ticks));

            for (int i = 0; i < 3000; i++) {
                var size = rnd.Next (3, 9);
                var data = new string [size];
                var junk = new string [size];

                data [0] = i.ToString ();
                junk [0] = "junk";

                for (int n = 1; n < size; n++) {
                    data [n] = rnd.Next ().ToString ();
                    junk [n] = Guid.NewGuid ().ToString ("N").Substring (0, size);
                }

                list.Add (new DocumentSample ("number", data));

                // random stuff
                list.Add (new DocumentSample ("junk", junk));
            }


            IObjectStream<DocumentSample> samples = new GenericObjectStream<DocumentSample>(list);

            var param = new TrainingParameters ();

            param.Set (Parameters.Algorithm, "MAXENT");
            param.Set (Parameters.TrainerType, "Event");
            param.Set (Parameters.Iterations, "5000");
            param.Set (Parameters.Cutoff, "4");
            param.Set (Parameters.Threads, "8");

            var factory = new DocumentCategorizerFactory ();
            var model = DocumentCategorizerME.Train ("en", samples, param, factory);
            var doccat = new DocumentCategorizerME (model);

            var probs = doccat.Categorize ("1322");

            var best = doccat.GetBestCategory (probs);

            Assert.AreEqual ("number", best);

        }
    }
}
```
