### ISSUE TITLE
Does the NER model created from Java version of OpenNLP for this NLP?

### ISSUE THREAD

**Issue by UNICASTERSOL** [knuppe/SharpNL#37]
Hello,

I was wondering does the Java version of NLP generated able to be used with this library for NER Namefind feature?

**Comment by knuppe** [comment]
Yes, you can use models from OpenNLP 1.5 and 1.6 without problem as far as I could [test](https://github.com/knuppe/SharpNL/tree/development/src/SharpNL.Tests/Compatibility).
