### ISSUE TITLE
Problems translating Java code to use with SharpNL

### ISSUE THREAD

**Issue by JCKodel** [knuppe/SharpNL#38]
I'm trying to port https://github.com/mlehman/nlp-intent-toolkit to C#, but some objects from opennlp seems not to be available in SharpNL.

For example:
```var combinedDocumentSampleStream = ObjectStreamUtils.createObjectStream(categoryStreams.ToArray());```

There are no ObjectStreamUtils available in SharpNL =\

**Comment by knuppe** [comment]
The commit works fine! AppVeyor had an issue, that's why the build did not work!

:+1:
