### ISSUE TITLE
How are you so awesome?

### ISSUE THREAD

**Issue by TechnikEmpire** [knuppe/SharpNL#39]
This is a bug that needs immediate solving. Are you simply a mountain of raw programming power, or did you do some automated translation and then fill in the gaps? I mean even if the latter, still a mountain of raw programming power.

Sorry to open a bug ticket for such a stupid reason but seriously this is a great find. Hopefully now I can kiss IKVM goodbye.

**Comment by TheQuack45** [comment]
You're absolutely right. This library is a work of art, and it is _way_ too obscure and hard to find.

**Comment by knuppe** [comment]
Wow!! I am very happy to see the compliments. I worked thousands of hours on this project, something close to 6 months of work, just for fun and curiosity, when I started, I had no knowledge about NLP, I just wanted to learn.

All code that exists was written by hand, without tools, I was simply solving one problem after another, to the point of being 100% compatible with the original version in Java.

I'm just passionate about programming!
