### ISSUE TITLE
How do I set a list of words that needs to be ignored with sentence detection

### ISSUE THREAD

**Issue by Sicos1977** [knuppe/SharpNL#6]
Hi,

A short question, how can I set a list of words that need to be ignored when using the sentence detection? For example I want to add words like "tel.", "12. This is an options" .... etc...
I want to add the words from code. I want to use a database table to store the words that need to be ignored.

I now use the code like this...

            using (var file = Tests.OpenFile("/opennlp/models/en-sent.bin")) {

                var model = new SentenceModel(file);
                var sentenceModel = new SentenceDetectorME(model);
                var sentences = sentenceModel.SentDetect("My text with sentences...");

                foreach (var sentence in sentences)
                {
                    // Do something....
                }
            }

Greetings,
Kees van Spelde

**Comment by knuppe** [comment]
The `en-sent.bin` is a "standard" model file to detect common English sentences. This model file was created/trained long time ago by the opennlp devs to test the library during the development. I believe it is not possible to use this model to do what you want.

In order to fit your needs, you could train a custom model using an abbreviation dictionary and a data file with some sentences containing those abbreviations.

You can find more information about the training processes in the opennlp [documentation](http://opennlp.apache.org/documentation/1.5.3/manual/opennlp.html#tools.sentdetect.training)

**Comment by Sicos1977** [comment]
Actually I use the "nl-sent.bin" file... since I'm processing Dutch text. The above code was just an example.

But what I just want to know is how I can add a list with words that need to be ignored. I know have that the sentence detection breaks this line in 2 sentences "12. Toedracht". Is there an option to do this?

Greetings,
Kees van Spelde

**Comment by Sicos1977** [comment]
Hi,

I wrote this code... but it doesn't work. What am I doing wrong? It keeps breaking of the sentence at the "12. Toedracht" and "tel." even when I have trained the model and added them to the abbreviation list.

            var sampleSentences1 = "Test E-mail met zowel letsel als 12. Toedracht in het onderwerp" +
                                   Environment.NewLine +
                                   "Dit is een 2e regel met een tel. 013-4621926 erin" + Environment.NewLine +
                                   "Dit is een 2e regel." + Environment.NewLine +
                                   "Dit is een 2e regel." + Environment.NewLine +
                                   "Dit is een 2e regel." + Environment.NewLine + Environment.NewLine +
                                   "Dit is een 2e regel!" + Environment.NewLine +
                                   "Dit is een 2e regel?" + Environment.NewLine +
                                   "Dit is een 2e regel.." + Environment.NewLine;

            var stringsToIgnoreDictionary = new SharpNL.Dictionary.Dictionary(false);
            //
            var tokens = new List<string>();
            tokens.Add("12. Toedracht");
            tokens.Add("Tel.");
            stringsToIgnoreDictionary.Add(new StringList(tokens.ToArray()));
            var trainingParameters = new TrainingParameters();

            trainingParameters.Set(Parameters.Algorithm, "MAXENT");
            trainingParameters.Set(Parameters.TrainerType, "Event");
            trainingParameters.Set(Parameters.Iterations, "100");
            trainingParameters.Set(Parameters.Cutoff, "5");

            char[] eos = { '.', '?' };
            var sdFactory = new SentenceDetectorFactory("nl", true, stringsToIgnoreDictionary, eos);
            var stringReader = new StringReader(sampleSentences1);
            var stream = new SentenceSampleStream(new PlainTextByLineStream(stringReader));

            var sentenceModel = SentenceDetectorME.Train("nl", stream, sdFactory, trainingParameters);
            var sentenceDetectorMe = new SentenceDetectorME(sentenceModel);
            var sents = sentenceDetectorMe.SentDetect(sampleSentences1);
            var probs = sentenceDetectorMe.GetSentenceProbabilities();

**Comment by knuppe** [comment]
You must provide more samples to train the model propperly. WIth more samples the model will learn how to avoid the splits.

 ```csharp 
            var sampleSentences1 = 
                "Test E-mail met zowel letsel als 12. Toedracht in het onderwerp." + Environment.NewLine +
                "Dit is een 2e regel met een tel. 011-4441444 erin" + Environment.NewLine +
                "Test E-mail met zowel winst als 12. Toedracht in het onderwerp." + Environment.NewLine +
                "Dit is een 2e regel met een tel. 013-4621926 erin." + Environment.NewLine +
                
                "Dit is een 2e regel." + Environment.NewLine 
                + Environment.NewLine +
                               
                "Dit is een 2e regel." + Environment.NewLine +
                "Dit is een 2e regel met een tel. 033-1333123 erin!" + Environment.NewLine +
                "Test E-mail met zowel winst als 12. Toedracht in het onderwerp." + Environment.NewLine +
                "Dit is een 2e regel!" + Environment.NewLine +
                "Dit is een 2e regel." + Environment.NewLine + Environment.NewLine +

                "Dit is een 2e regel." + Environment.NewLine +
                "Dit is een 2e regel tel. 133-23331 erin." + Environment.NewLine +
                "Test E-mail met zowel winst als 12. Toedracht in het onderwerp." + Environment.NewLine +
                "Test E-mail met zowel winst als 13. Toedracht in het onderwerp." + Environment.NewLine +
                "Test E-mail met onderwerp letsel een 12. Toedracht in het dit." + Environment.NewLine;
                                                                 
            var stringsToIgnoreDictionary = new SharpNL.Dictionary.Dictionary(false) {
                {"12. Toedracht"},
                {"Tel."},
                {"tel."}
            };

            var trainingParameters = new TrainingParameters();

            trainingParameters.Set(Parameters.Algorithm, "MAXENT");
            trainingParameters.Set(Parameters.TrainerType, "Event");
            trainingParameters.Set(Parameters.Iterations, "100");
            trainingParameters.Set(Parameters.Cutoff, "5");

            char[] eos = { '.', '?', '!' };
            var sdFactory = new SentenceDetectorFactory("nl", true, stringsToIgnoreDictionary, eos);
            var stringReader = new StringReader(sampleSentences1);
            var stream = new SentenceSampleStream(new PlainTextByLineStream(stringReader));

            var sentenceModel = SentenceDetectorME.Train("nl", stream, sdFactory, trainingParameters);
            var sentenceDetectorMe = new SentenceDetectorME(sentenceModel);

            var sents = sentenceDetectorMe.SentDetect(sampleSentences1);
            var probs = sentenceDetectorMe.GetSentenceProbabilities();
```
