### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by Sicos1977** [knuppe/SharpNL#7]
Hi,

Why are you converting a Dictionary to a List this way? This way only the first token is returned even when you add like 10 tokens

        #region . ToList .
        /// <summary>
        /// Converts the dictionary to a <see cref="List{T}"/>.
        /// </summary>
        /// <returns>A string list object.</returns>
        public virtual List<string> ToList() {
            var toList = new List<string>();
            var e = GetEnumerator();

            while (e.MoveNext()) {
                toList.Add(e.Current.Tokens[0]);
            }

            return toList;
        }
        #endregion

Would it not be better to do this instead?

            while (e.MoveNext()) {
                toList.AddRange(e.Current.Tokens);

**Comment by knuppe** [comment]
It's a good question, I just ported the original [java class](https://github.com/apache/opennlp/blob/trunk/opennlp-tools/src/main/java/opennlp/tools/dictionary/Dictionary.java#L330) and original code has the same behaviour.

Usually abbreviations word that has "significance" is only the first, but do not believe it is applicable to all cases.

**Comment by Sicos1977** [comment]
I also extended the SentenceDetectorME class

        public SentenceDetectorME(SentenceModel sentenceModel) {
            model = sentenceModel.MaxentModel;
            cgen = sentenceModel.Factory.GetContextGenerator();
            scanner = sentenceModel.Factory.GetEndOfSentenceScanner();
            useTokenEnd = sentenceModel.UseTokenEnd;
            _abbriviations = sentenceModel.Abbreviations;
        }

And changed this method so that the abbriviation list works.. the training seemed to ignore the abbriviation list.

        protected virtual bool IsAcceptableBreak(String s, int fromIndex, int candidateIndex)
        {
            if (_abbriviations == null)
                return true;

            foreach (var abbriviation in _abbriviations)
            {
                var token = abbriviation.Tokens[0];
                var tokenLength = token.Length;

                var tokenPosition = s.IndexOf(token, fromIndex, StringComparison.InvariantCultureIgnoreCase);
                if (tokenPosition + tokenLength < candidateIndex || tokenPosition > candidateIndex) continue;
                return false;
            }

            return true;
        }
        #endregion

**Comment by knuppe** [comment]
Theoretically well-trained models should deal very well with abbreviations, but I agree with your change in the default behaviour. Thanks!
